name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore GetOptTests
    - name: Build
      run: dotnet build GetOptTests --configuration Release --no-restore
    - name: Test
      run: dotnet test GetOptTests --configuration Release --no-restore --no-build --verbosity normal
    - name: Create artifacts
      uses: actions/upload-artifact@v1
      with:
        name: NuGet Package
        path: GetOpt/bin/Release/GetOpt.NET.1.0.0.nupkg

